import type { PantryItem } from '@backend/lib/db'

export const mockPantry: PantryItem[] = [
  {
    name: 'Extra Fine Bread Flour',
    category: 'Ingredients',
    currentStock: 25,
    minStock: 10,
    unit: 'bags',
    lastPrice: 180,
    status: 'In Stock',
    notes: 'Premium wheat flour for sourdough',
    updatedAt: new Date(),
    createdAt: new Date()
  },
  {
    name: 'Granulated White Sugar',
    category: 'Ingredients',
    currentStock: 4,
    minStock: 10,
    unit: 'bags',
    lastPrice: 95,
    status: 'Low Stock',
    notes: 'Bulk purchase from Central Market',
    updatedAt: new Date(),
    createdAt: new Date()
  },
  {
    name: 'Unsalted Butter',
    category: 'Ingredients',
    currentStock: 15,
    minStock: 20,
    unit: 'kg',
    lastPrice: 45,
    status: 'Low Stock',
    notes: 'Keep refrigerated',
    updatedAt: new Date(),
    createdAt: new Date()
  },
  {
    name: 'Large Brown Eggs',
    category: 'Ingredients',
    currentStock: 12,
    minStock: 5,
    unit: 'crates',
    lastPrice: 35,
    status: 'In Stock',
    notes: 'Fresh farm delivery every Monday',
    updatedAt: new Date(),
    createdAt: new Date()
  },
  {
    name: 'Luxury Cake Boxes',
    category: 'Packaging',
    currentStock: 50,
    minStock: 100,
    unit: 'pieces',
    lastPrice: 5.5,
    status: 'Low Stock',
    notes: 'Branded with gold foil',
    updatedAt: new Date(),
    createdAt: new Date()
  },
  {
    name: 'Vanilla Extract',
    category: 'Ingredients',
    currentStock: 0,
    minStock: 2,
    unit: 'liters',
    lastPrice: 120,
    status: 'Out of Stock',
    notes: 'Madagascar Bourbon variety',
    updatedAt: new Date(),
    createdAt: new Date()
  },
  {
    name: 'Baking Powder',
    category: 'Ingredients',
    currentStock: 8,
    minStock: 3,
    unit: 'kg',
    lastPrice: 22,
    status: 'In Stock',
    updatedAt: new Date(),
    createdAt: new Date()
  },
  {
    name: 'Heavy Duty Dish Soap',
    category: 'Cleaning',
    currentStock: 5,
    minStock: 2,
    unit: 'liters',
    lastPrice: 15,
    status: 'In Stock',
    updatedAt: new Date(),
    createdAt: new Date()
  },
  {
    name: 'Dark Chocolate Chips',
    category: 'Toppings',
    currentStock: 10,
    minStock: 5,
    unit: 'kg',
    lastPrice: 65,
    status: 'In Stock',
    notes: '70% Cocoa',
    updatedAt: new Date(),
    createdAt: new Date()
  },
  {
    name: 'Rainbow Sprinkles',
    category: 'Toppings',
    currentStock: 2,
    minStock: 5,
    unit: 'kg',
    lastPrice: 12,
    status: 'Low Stock',
    updatedAt: new Date(),
    createdAt: new Date()
  },
  {
    name: 'Kraft Paper Bags',
    category: 'Packaging',
    currentStock: 500,
    minStock: 200,
    unit: 'pieces',
    lastPrice: 0.8,
    status: 'In Stock',
    updatedAt: new Date(),
    createdAt: new Date()
  },
  {
    name: 'Whole Milk',
    category: 'Ingredients',
    currentStock: 24,
    minStock: 12,
    unit: 'liters',
    lastPrice: 18,
    status: 'In Stock',
    updatedAt: new Date(),
    createdAt: new Date()
  },
  {
    name: 'Cocoa Powder',
    category: 'Ingredients',
    currentStock: 3,
    minStock: 5,
    unit: 'kg',
    lastPrice: 40,
    status: 'Low Stock',
    updatedAt: new Date(),
    createdAt: new Date()
  },
  {
    name: 'Instant Yeast',
    category: 'Ingredients',
    currentStock: 1,
    minStock: 2,
    unit: 'kg',
    lastPrice: 55,
    status: 'Low Stock',
    updatedAt: new Date(),
    createdAt: new Date()
  },
  {
    name: 'Cinnamon Powder',
    category: 'Ingredients',
    currentStock: 0.5,
    minStock: 1,
    unit: 'kg',
    lastPrice: 30,
    status: 'Low Stock',
    updatedAt: new Date(),
    createdAt: new Date()
  },
  {
    name: 'Salt (Sea Salt)',
    category: 'Ingredients',
    currentStock: 10,
    minStock: 2,
    unit: 'kg',
    lastPrice: 5,
    status: 'In Stock',
    updatedAt: new Date(),
    createdAt: new Date()
  },
  {
    name: 'Aluminum Foil',
    category: 'Packaging',
    currentStock: 5,
    minStock: 10,
    unit: 'boxes',
    lastPrice: 25,
    status: 'Low Stock',
    updatedAt: new Date(),
    createdAt: new Date()
  },
  {
    name: 'Sanitizer Spray',
    category: 'Cleaning',
    currentStock: 10,
    minStock: 4,
    unit: 'liters',
    lastPrice: 45,
    status: 'In Stock',
    updatedAt: new Date(),
    createdAt: new Date()
  },
  {
    name: 'Paper Towels',
    category: 'Cleaning',
    currentStock: 2,
    minStock: 12,
    unit: 'boxes',
    lastPrice: 60,
    status: 'Low Stock',
    updatedAt: new Date(),
    createdAt: new Date()
  },
  {
    name: 'Honey',
    category: 'Ingredients',
    currentStock: 5,
    minStock: 2,
    unit: 'liters',
    lastPrice: 85,
    status: 'In Stock',
    updatedAt: new Date(),
    createdAt: new Date()
  },
  {
    name: 'Walnuts',
    category: 'Toppings',
    currentStock: 0,
    minStock: 3,
    unit: 'kg',
    lastPrice: 110,
    status: 'Out of Stock',
    updatedAt: new Date(),
    createdAt: new Date()
  },
  {
    name: 'Parchment Paper',
    category: 'Packaging',
    currentStock: 3,
    minStock: 5,
    unit: 'boxes',
    lastPrice: 15,
    status: 'Low Stock',
    updatedAt: new Date(),
    createdAt: new Date()
  },
  {
    name: 'Brown Sugar',
    category: 'Ingredients',
    currentStock: 20,
    minStock: 5,
    unit: 'kg',
    lastPrice: 12,
    status: 'In Stock',
    updatedAt: new Date(),
    createdAt: new Date()
  },
  {
    name: 'Cake Flour',
    category: 'Ingredients',
    currentStock: 15,
    minStock: 10,
    unit: 'bags',
    lastPrice: 175,
    status: 'In Stock',
    updatedAt: new Date(),
    createdAt: new Date()
  },
  {
    name: 'Pastry Flour',
    category: 'Ingredients',
    currentStock: 5,
    minStock: 8,
    unit: 'bags',
    lastPrice: 165,
    status: 'Low Stock',
    updatedAt: new Date(),
    createdAt: new Date()
  },
  {
    name: 'Coconut Flakes',
    category: 'Toppings',
    currentStock: 8,
    minStock: 4,
    unit: 'kg',
    lastPrice: 35,
    status: 'In Stock',
    updatedAt: new Date(),
    createdAt: new Date()
  },
  {
    name: 'Powdered Sugar',
    category: 'Ingredients',
    currentStock: 12,
    minStock: 5,
    unit: 'kg',
    lastPrice: 15,
    status: 'In Stock',
    updatedAt: new Date(),
    createdAt: new Date()
  },
  {
    name: 'Condensed Milk',
    category: 'Ingredients',
    currentStock: 48,
    minStock: 24,
    unit: 'pieces',
    lastPrice: 12,
    status: 'In Stock',
    updatedAt: new Date(),
    createdAt: new Date()
  },
  {
    name: 'Cornstarch',
    category: 'Ingredients',
    currentStock: 5,
    minStock: 2,
    unit: 'kg',
    lastPrice: 20,
    status: 'In Stock',
    updatedAt: new Date(),
    createdAt: new Date()
  },
  {
    name: 'Gold Leaf Sheets',
    category: 'Toppings',
    currentStock: 2,
    minStock: 1,
    unit: 'pieces',
    lastPrice: 250,
    status: 'In Stock',
    updatedAt: new Date(),
    createdAt: new Date()
  },
  {
    name: 'Edible Flowers',
    category: 'Toppings',
    currentStock: 0,
    minStock: 5,
    unit: 'pieces',
    lastPrice: 45,
    status: 'Out of Stock',
    updatedAt: new Date(),
    createdAt: new Date()
  },
  {
    name: 'Cupcake Liners (Gold)',
    category: 'Packaging',
    currentStock: 1000,
    minStock: 500,
    unit: 'pieces',
    lastPrice: 0.1,
    status: 'In Stock',
    updatedAt: new Date(),
    createdAt: new Date()
  },
  {
    name: 'Cupcake Liners (White)',
    category: 'Packaging',
    currentStock: 200,
    minStock: 500,
    unit: 'pieces',
    lastPrice: 0.05,
    status: 'Low Stock',
    updatedAt: new Date(),
    createdAt: new Date()
  },
  {
    name: 'Baker\'s Twine (Red/White)',
    category: 'Packaging',
    currentStock: 10,
    minStock: 5,
    unit: 'pieces',
    lastPrice: 15,
    status: 'In Stock',
    updatedAt: new Date(),
    createdAt: new Date()
  },
  {
    name: 'Glass Jars (Small)',
    category: 'Packaging',
    currentStock: 24,
    minStock: 48,
    unit: 'pieces',
    lastPrice: 8,
    status: 'Low Stock',
    updatedAt: new Date(),
    createdAt: new Date()
  },
  {
    name: 'Disposable Gloves (M)',
    category: 'Cleaning',
    currentStock: 5,
    minStock: 10,
    unit: 'boxes',
    lastPrice: 40,
    status: 'Low Stock',
    updatedAt: new Date(),
    createdAt: new Date()
  },
  {
    name: 'Kitchen Aprons',
    category: 'Cleaning',
    currentStock: 12,
    minStock: 5,
    unit: 'pieces',
    lastPrice: 35,
    status: 'In Stock',
    updatedAt: new Date(),
    createdAt: new Date()
  },
  {
    name: 'Microfiber Cloths',
    category: 'Cleaning',
    currentStock: 20,
    minStock: 10,
    unit: 'pieces',
    lastPrice: 5,
    status: 'In Stock',
    updatedAt: new Date(),
    createdAt: new Date()
  },
  {
    name: 'All-Purpose Cleaner',
    category: 'Cleaning',
    currentStock: 4,
    minStock: 6,
    unit: 'liters',
    lastPrice: 28,
    status: 'Low Stock',
    updatedAt: new Date(),
    createdAt: new Date()
  },
  {
    name: 'Dried Lavender',
    category: 'Toppings',
    currentStock: 1,
    minStock: 0.5,
    unit: 'kg',
    lastPrice: 90,
    status: 'In Stock',
    updatedAt: new Date(),
    createdAt: new Date()
  },
  {
    name: 'Sliced Almonds',
    category: 'Toppings',
    currentStock: 15,
    minStock: 5,
    unit: 'kg',
    lastPrice: 85,
    status: 'In Stock',
    updatedAt: new Date(),
    createdAt: new Date()
  },
  {
    name: 'Matcha Powder',
    category: 'Ingredients',
    currentStock: 0.5,
    minStock: 2,
    unit: 'kg',
    lastPrice: 240,
    status: 'Low Stock',
    updatedAt: new Date(),
    createdAt: new Date()
  },
  {
    name: 'Molasses',
    category: 'Ingredients',
    currentStock: 6,
    minStock: 2,
    unit: 'liters',
    lastPrice: 55,
    status: 'In Stock',
    updatedAt: new Date(),
    createdAt: new Date()
  },
  {
    name: 'Baking Soda',
    category: 'Ingredients',
    currentStock: 10,
    minStock: 5,
    unit: 'kg',
    lastPrice: 15,
    status: 'In Stock',
    updatedAt: new Date(),
    createdAt: new Date()
  },
  {
    name: 'Sticker Labels (Branded)',
    category: 'Packaging',
    currentStock: 2000,
    minStock: 500,
    unit: 'pieces',
    lastPrice: 0.2,
    status: 'In Stock',
    updatedAt: new Date(),
    createdAt: new Date()
  }

]
